
import React, { useState, useMemo } from 'react';
import { AnalysisStatus } from '../types';
import { Bot, Loader2, RefreshCw, Copy, Download, Check } from 'lucide-react';
import clsx from 'clsx';

interface AnalysisCardProps {
  title: string;
  status: AnalysisStatus;
  result: string | null;
  onAnalyze: () => void;
  description: string;
  repoName?: string;
  disabled?: boolean;
}

const AnalysisCard: React.FC<AnalysisCardProps> = ({ title, status, result, onAnalyze, description, repoName, disabled }) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    if (!result) return;
    navigator.clipboard.writeText(result);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    if (!result) return;
    const blob = new Blob([result], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${title.replace(/\s+/g, '_').toLowerCase()}_report.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Auto-linkify Issue #123 and PR #123 references if repoName is provided
  // We process the result string before rendering to inject markdown links
  const linkifiedResult = useMemo(() => {
    if (!result || !repoName) return result;
    
    // Regex to match #123, Issue #123, PR #123
    // It looks for a preceding space, start of line, or bracket to avoid double linking
    return result.replace(/(^|\s|\(|\[)(?:Issue|PR)?\s?#(\d+)\b/g, (match, prefix, number) => {
        // If it's already a markdown link (e.g. [#123](url)), this regex might need to be smarter,
        // but for plain text generated by AI, this simple approach usually works well.
        return `${prefix}[${match.trim()}](${`https://github.com/${repoName}/issues/${number}`})`;
    });
  }, [result, repoName]);

  return (
    <div className="bg-surface border border-slate-700 rounded-xl overflow-hidden shadow-lg mb-6">
      <div className="p-6 border-b border-slate-700 flex justify-between items-center bg-slate-800/50">
        <div>
          <h3 className="text-xl font-semibold text-white flex items-center gap-2">
            <Bot className="w-5 h-5 text-primary" />
            {title}
          </h3>
          <p className="text-sm text-secondary mt-1">{description}</p>
        </div>
        <button
          onClick={onAnalyze}
          disabled={status === AnalysisStatus.LOADING || disabled}
          className={clsx(
            "flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-colors",
            (status === AnalysisStatus.LOADING || disabled)
              ? "bg-slate-700 text-slate-400 cursor-not-allowed"
              : "bg-primary hover:bg-blue-600 text-white shadow-md shadow-blue-500/20"
          )}
        >
          {status === AnalysisStatus.LOADING ? (
            <>
              <Loader2 className="w-4 h-4 animate-spin" />
              Thinking...
            </>
          ) : (
            <>
              <RefreshCw className="w-4 h-4" />
              Run Analysis
            </>
          )}
        </button>
      </div>
      
      <div className="p-6">
        {status === AnalysisStatus.IDLE && !result && (
          <div className="text-center py-12 text-slate-500 bg-slate-900/50 rounded-lg border border-dashed border-slate-700">
            <Bot className="w-12 h-12 mx-auto mb-3 opacity-20" />
            <p>Ready to analyze repository data.</p>
            <p className="text-sm">Click "Run Analysis" to generate insights with Gemini 2.5 Flash.</p>
          </div>
        )}

        {status === AnalysisStatus.ERROR && (
           <div className="p-4 bg-red-900/20 border border-red-800 text-red-200 rounded-lg">
             Error running analysis. Please check your API keys and try again.
           </div>
        )}

        {result && (
          <div className="prose prose-invert prose-blue max-w-none">
            <div className="bg-slate-900/50 rounded-lg border border-slate-700 overflow-hidden">
               {/* Toolbar */}
               <div className="flex justify-between items-center px-4 py-2 bg-slate-800/50 border-b border-slate-700">
                  <span className="text-xs text-slate-500 font-mono uppercase">Markdown Output</span>
                  <div className="flex items-center gap-2">
                    <button 
                      onClick={handleCopy} 
                      className="p-1.5 text-slate-400 hover:text-white hover:bg-slate-700 rounded transition-colors"
                      title="Copy to Clipboard"
                    >
                      {copied ? <Check className="w-4 h-4 text-green-500" /> : <Copy className="w-4 h-4" />}
                    </button>
                    <button 
                      onClick={handleDownload} 
                      className="p-1.5 text-slate-400 hover:text-white hover:bg-slate-700 rounded transition-colors"
                      title="Download as Markdown"
                    >
                      <Download className="w-4 h-4" />
                    </button>
                  </div>
               </div>

               <div className="p-6 whitespace-pre-wrap font-sans text-slate-300 leading-relaxed">
                 {/* 
                   We parse the markdown manually for simple display 
                   but use the linkifiedResult which has injected Markdown links.
                 */}
                 {(linkifiedResult || result).split('\n').map((line, i) => {
                    // Simple regex to detect markdown links [text](url) and render as <a>
                    const linkRegex = /\[([^\]]+)\]\(([^)]+)\)/g;
                    const parts = [];
                    let lastIndex = 0;
                    let match;
                    
                    while ((match = linkRegex.exec(line)) !== null) {
                        if (match.index > lastIndex) {
                            parts.push(line.substring(lastIndex, match.index));
                        }
                        parts.push(<a key={`${i}-${match.index}`} href={match[2]} target="_blank" rel="noopener noreferrer" className="text-blue-400 hover:underline">{match[1]}</a>);
                        lastIndex = linkRegex.lastIndex;
                    }
                    if (lastIndex < line.length) {
                        parts.push(line.substring(lastIndex));
                    }

                    const content = parts.length > 0 ? parts : line;

                    if (line.startsWith('###')) return <h3 key={i} className="text-lg font-bold text-white mt-4 mb-2">{content}</h3>
                    if (line.startsWith('##')) return <h2 key={i} className="text-xl font-bold text-blue-400 mt-6 mb-3">{content}</h2>
                    if (line.startsWith('#')) return <h1 key={i} className="text-2xl font-bold text-white mt-6 mb-4">{content}</h1>
                    if (line.startsWith('-')) return <li key={i} className="ml-4 text-slate-300">{content}</li>
                    if (line.startsWith('**')) return <strong key={i} className="block mt-2 text-white">{line.replace(/\*\*/g, '')}</strong>
                    return <p key={i} className="mb-2">{content}</p>
                 })}
               </div>
            </div>
            <div className="mt-4 flex justify-end">
              <span className="text-xs text-slate-500 uppercase tracking-wider">Generated by Gemini 2.5 Flash</span>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default AnalysisCard;