
import React, { useState } from 'react';
import { 
  Bot, Sparkles, Trash2, Link as LinkIcon, AlertTriangle, 
  ArrowRight, Check, Play, Loader2, Zap, Target, Wrench, Search,
  Code2, FileSearch, ShieldCheck, Box
} from 'lucide-react';
import clsx from 'clsx';
import { fetchIssues, fetchPullRequests, createIssue, updateIssue, addComment } from '../services/githubService';
import { suggestStrategicIssues, auditPullRequests, findIssuePrLinks } from '../services/geminiService';
import { ProposedIssue, PrActionRecommendation, LinkSuggestion, AnalysisStatus } from '../types';

interface AgentProps {
  repoName: string;
  token: string;
}

// Extended types with local ID for selection tracking
type ProposedIssueWithId = ProposedIssue & { _id: string };
type PrActionWithId = PrActionRecommendation & { _id: string };
type LinkSuggestionWithId = LinkSuggestion & { _id: string };

const generateId = () => Math.random().toString(36).substr(2, 9);

const Agent: React.FC<AgentProps> = ({ repoName, token }) => {
  const [activeTab, setActiveTab] = useState<'architect' | 'overseer' | 'janitor'>('architect');
  const [bulkProcessing, setBulkProcessing] = useState(false);
  
  // Architect State
  const [proposedIssues, setProposedIssues] = useState<ProposedIssueWithId[]>([]);
  const [architectStatus, setArchitectStatus] = useState<AnalysisStatus>(AnalysisStatus.IDLE);
  const [selectedIssueIds, setSelectedIssueIds] = useState<Set<string>>(new Set());
  const [discoveryMode, setDiscoveryMode] = useState<string>('strategic');
  const [userGuidance, setUserGuidance] = useState('');
  
  // Overseer State
  const [prActions, setPrActions] = useState<PrActionWithId[]>([]);
  const [overseerStatus, setOverseerStatus] = useState<AnalysisStatus>(AnalysisStatus.IDLE);
  const [selectedActionIds, setSelectedActionIds] = useState<Set<string>>(new Set());

  // Janitor State
  const [links, setLinks] = useState<LinkSuggestionWithId[]>([]);
  const [janitorStatus, setJanitorStatus] = useState<AnalysisStatus>(AnalysisStatus.IDLE);
  const [selectedLinkIds, setSelectedLinkIds] = useState<Set<string>>(new Set());

  // --- Handlers ---

  // 1. Architect Handlers
  const runArchitect = async () => {
    setArchitectStatus(AnalysisStatus.LOADING);
    try {
      const [issues, prs] = await Promise.all([
        fetchIssues(repoName, token, 'open'),
        fetchPullRequests(repoName, token, 'open')
      ]);
      const suggestions = await suggestStrategicIssues(issues, prs, discoveryMode, userGuidance);
      setProposedIssues(suggestions.map(s => ({ ...s, _id: generateId() })));
      setSelectedIssueIds(new Set());
      setArchitectStatus(AnalysisStatus.COMPLETE);
    } catch (e) {
      setArchitectStatus(AnalysisStatus.ERROR);
    }
  };

  const executeCreateIssue = async (issue: ProposedIssueWithId) => {
    if (!token) return alert('Token required');
    try {
      // Append Effort label automatically
      const finalLabels = [...issue.labels, `effort:${issue.effort.toLowerCase()}`];
      
      await createIssue(repoName, token, {
        title: issue.title,
        body: issue.body + `\n\n*Generated by RepoAuditor Agent (${discoveryMode})*`,
        labels: finalLabels
      });
      setProposedIssues(prev => prev.filter(i => i._id !== issue._id));
      setSelectedIssueIds(prev => {
        const next = new Set(prev);
        next.delete(issue._id);
        return next;
      });
    } catch (e: any) {
      console.error(e);
      alert('Failed: ' + e.message);
    }
  };

  const executeBulkIssues = async () => {
    if (!token) return alert('Token required');
    setBulkProcessing(true);
    const selected = proposedIssues.filter(i => selectedIssueIds.has(i._id));
    const successIds: string[] = [];
    
    for (const issue of selected) {
      try {
        const finalLabels = [...issue.labels, `effort:${issue.effort.toLowerCase()}`];
        await createIssue(repoName, token, {
          title: issue.title,
          body: issue.body + `\n\n*Generated by RepoAuditor Agent (${discoveryMode})*`,
          labels: finalLabels
        });
        successIds.push(issue._id);
      } catch (e) {
        console.error(`Failed to create issue ${issue.title}`, e);
      }
    }

    // Batch update state
    setProposedIssues(prev => prev.filter(i => !successIds.includes(i._id)));
    setSelectedIssueIds(prev => {
       const next = new Set(prev);
       successIds.forEach(id => next.delete(id));
       return next;
    });
    setBulkProcessing(false);
  };

  // 2. Overseer Handlers
  const runOverseer = async () => {
    setOverseerStatus(AnalysisStatus.LOADING);
    try {
      const prs = await fetchPullRequests(repoName, token, 'open');
      const actions = await auditPullRequests(prs);
      setPrActions(actions.map(a => ({ ...a, _id: generateId() })));
      setSelectedActionIds(new Set());
      setOverseerStatus(AnalysisStatus.COMPLETE);
    } catch (e) {
      setOverseerStatus(AnalysisStatus.ERROR);
    }
  };

  const executePrAction = async (item: PrActionWithId) => {
    if (!token) return alert('Token required');
    try {
      if (item.action === 'close') {
        await updateIssue(repoName, token, item.prNumber, { state: 'closed' });
        if (item.suggestedComment) {
             await addComment(repoName, token, item.prNumber, item.suggestedComment);
        }
      } else if (item.action === 'comment' && item.suggestedComment) {
        await addComment(repoName, token, item.prNumber, item.suggestedComment);
      }
      
      setPrActions(prev => prev.filter(i => i._id !== item._id));
      setSelectedActionIds(prev => {
        const next = new Set(prev);
        next.delete(item._id);
        return next;
      });
    } catch (e: any) {
      alert('Failed: ' + e.message);
    }
  };

  const executeBulkActions = async () => {
    if (!token) return alert('Token required');
    setBulkProcessing(true);
    const selected = prActions.filter(i => selectedActionIds.has(i._id));
    const successIds: string[] = [];

    for (const item of selected) {
      try {
         if (item.action === 'close') {
            await updateIssue(repoName, token, item.prNumber, { state: 'closed' });
            if (item.suggestedComment) await addComment(repoName, token, item.prNumber, item.suggestedComment);
         } else if (item.action === 'comment' && item.suggestedComment) {
            await addComment(repoName, token, item.prNumber, item.suggestedComment);
         }
         successIds.push(item._id);
      } catch (e) {
        console.error(`Failed to execute action on PR #${item.prNumber}`, e);
      }
    }
    
    // Batch update state
    setPrActions(prev => prev.filter(i => !successIds.includes(i._id)));
    setSelectedActionIds(prev => {
       const next = new Set(prev);
       successIds.forEach(id => next.delete(id));
       return next;
    });
    setBulkProcessing(false);
  };

  // 3. Janitor Handlers
  const runJanitor = async () => {
    setJanitorStatus(AnalysisStatus.LOADING);
    try {
       const [issues, prs] = await Promise.all([
        fetchIssues(repoName, token, 'open'),
        fetchPullRequests(repoName, token, 'open')
      ]);
      const matches = await findIssuePrLinks(issues, prs);
      setLinks(matches.map(m => ({ ...m, _id: generateId() })));
      setSelectedLinkIds(new Set());
      setJanitorStatus(AnalysisStatus.COMPLETE);
    } catch (e) {
      setJanitorStatus(AnalysisStatus.ERROR);
    }
  };

  const executeLink = async (link: LinkSuggestionWithId) => {
    if (!token) return alert('Token required');
    try {
      const comment = `Closes #${link.issueNumber}\n\n*Linked by RepoAuditor Agent*`;
      await addComment(repoName, token, link.prNumber, comment);
      setLinks(prev => prev.filter(i => i._id !== link._id));
      setSelectedLinkIds(prev => {
        const next = new Set(prev);
        next.delete(link._id);
        return next;
      });
    } catch (e: any) {
      alert('Failed: ' + e.message);
    }
  };

  const executeBulkLinks = async () => {
    if (!token) return alert('Token required');
    setBulkProcessing(true);
    const selected = links.filter(i => selectedLinkIds.has(i._id));
    const successIds: string[] = [];

    for (const link of selected) {
      try {
        const comment = `Closes #${link.issueNumber}\n\n*Linked by RepoAuditor Agent*`;
        await addComment(repoName, token, link.prNumber, comment);
        successIds.push(link._id);
      } catch (e) {
        console.error(`Failed to link PR #${link.prNumber}`, e);
      }
    }
    
    // Batch update state
    setLinks(prev => prev.filter(i => !successIds.includes(i._id)));
    setSelectedLinkIds(prev => {
       const next = new Set(prev);
       successIds.forEach(id => next.delete(id));
       return next;
    });
    setBulkProcessing(false);
  };

  // --- Selection Helpers ---

  const toggleSelection = (setIds: Set<string>, setFunction: (s: Set<string>) => void, id: string) => {
    const newSet = new Set(setIds);
    if (newSet.has(id)) newSet.delete(id);
    else newSet.add(id);
    setFunction(newSet);
  };

  const toggleSelectAll = (ids: string[], currentSet: Set<string>, setFunction: (s: Set<string>) => void) => {
    if (currentSet.size === ids.length && ids.length > 0) {
      setFunction(new Set());
    } else {
      setFunction(new Set(ids));
    }
  };

  const discoveryOptions = [
    { value: 'strategic', label: 'Strategic Gaps', icon: Target },
    { value: 'tech_debt', label: 'Tech Debt (General)', icon: Wrench },
    { value: 'quick_win', label: 'Quick Wins', icon: Zap },
    { value: 'code_reuse', label: 'Code Reuse & Utilities', icon: Code2 },
    { value: 'dead_code', label: 'Dead Code / Deprecation', icon: Trash2 },
    { value: 'readability', label: 'Naming & Readability', icon: FileSearch },
    { value: 'maintainability', label: 'Maintenance & Updates', icon: Box },
  ];

  return (
    <div className="max-w-6xl mx-auto pb-20">
      <div className="flex items-center gap-3 mb-8">
        <div className="bg-purple-500/20 p-3 rounded-lg text-purple-400">
           <Bot className="w-8 h-8" />
        </div>
        <div>
          <h2 className="text-2xl font-bold text-white">Repo Agent</h2>
          <p className="text-slate-400">Autonomous assistant to suggest work, triage PRs, and clean up the repo.</p>
        </div>
      </div>

      {/* Tabs */}
      <div className="flex border-b border-slate-700 mb-8 overflow-x-auto">
        {[
          { id: 'architect', label: 'Architect (Discovery)', icon: Sparkles },
          { id: 'overseer', label: 'Overseer (PR Triage)', icon: AlertTriangle },
          { id: 'janitor', label: 'Janitor (Cleanup)', icon: Trash2 },
        ].map((tab) => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id as any)}
            className={clsx(
              "flex items-center gap-2 px-6 py-4 font-medium transition-colors border-b-2 whitespace-nowrap",
              activeTab === tab.id
                ? "border-primary text-primary"
                : "border-transparent text-slate-400 hover:text-white"
            )}
          >
            <tab.icon className="w-4 h-4" />
            {tab.label}
          </button>
        ))}
      </div>

      {/* --- ARCHITECT TAB --- */}
      {activeTab === 'architect' && (
        <div className="space-y-6">
          <div className="bg-surface border border-slate-700 rounded-xl p-6">
            <div className="mb-6">
                 <h3 className="text-xl font-bold text-white">Issue Discovery Engine</h3>
                 <p className="text-sm text-slate-400 mt-1">Configure the agent to find specific types of work.</p>
            </div>
            
            {/* Control Panel */}
            <div className="bg-slate-900/50 p-5 rounded-lg border border-slate-700 mb-6 grid grid-cols-1 lg:grid-cols-12 gap-4 items-end">
               <div className="lg:col-span-3">
                 <label className="block text-xs font-bold text-slate-500 uppercase mb-2">Discovery Mode</label>
                 <div className="relative">
                   <select 
                     value={discoveryMode}
                     onChange={(e) => setDiscoveryMode(e.target.value)}
                     className="w-full bg-slate-800 border border-slate-600 text-white text-sm rounded-lg p-2.5 appearance-none focus:ring-1 focus:ring-primary focus:border-primary"
                   >
                     {discoveryOptions.map(opt => (
                       <option key={opt.value} value={opt.value}>{opt.label}</option>
                     ))}
                   </select>
                   <div className="absolute inset-y-0 right-0 flex items-center pr-3 pointer-events-none text-slate-400">
                     <Search className="w-4 h-4" />
                   </div>
                 </div>
               </div>

               <div className="lg:col-span-7">
                  <label className="block text-xs font-bold text-slate-500 uppercase mb-2">User Guidance (Optional)</label>
                  <input 
                    type="text"
                    value={userGuidance}
                    onChange={(e) => setUserGuidance(e.target.value)}
                    placeholder="E.g. Focus on the authentication flow, or check the header component..."
                    className="w-full bg-slate-800 border border-slate-600 text-white text-sm rounded-lg p-2.5 focus:ring-1 focus:ring-primary focus:border-primary placeholder-slate-600"
                  />
               </div>

               <div className="lg:col-span-2">
                 <button 
                  onClick={runArchitect}
                  disabled={architectStatus === AnalysisStatus.LOADING || bulkProcessing}
                  className="w-full bg-primary hover:bg-blue-600 text-white p-2.5 rounded-lg font-medium flex items-center justify-center gap-2 border border-blue-500 shadow-lg shadow-blue-500/20 transition-all"
                >
                  {architectStatus === AnalysisStatus.LOADING ? <Loader2 className="animate-spin w-4 h-4"/> : <Sparkles className="w-4 h-4"/>}
                  Generate
                </button>
               </div>
            </div>

            {/* Actions Bar */}
            {proposedIssues.length > 0 && (
               <div className="flex items-center justify-between mb-4 bg-slate-800/30 p-3 rounded-lg border border-slate-700/50">
                  <div className="flex items-center gap-3">
                     <div className="flex items-center gap-2">
                       <input 
                          type="checkbox"
                          checked={proposedIssues.length > 0 && selectedIssueIds.size === proposedIssues.length}
                          onChange={() => toggleSelectAll(proposedIssues.map(i => i._id), selectedIssueIds, setSelectedIssueIds)}
                          className="w-4 h-4 rounded border-slate-600 bg-slate-800 text-purple-600 focus:ring-0 cursor-pointer"
                       />
                       <span className="text-sm text-slate-300 whitespace-nowrap">Select All</span>
                     </div>
                     <span className="text-slate-600">|</span>
                     <span className="text-sm text-slate-400">Found {proposedIssues.length} suggestions</span>
                  </div>
                  <button 
                    onClick={executeBulkIssues}
                    disabled={selectedIssueIds.size === 0 || bulkProcessing}
                    className={clsx(
                      "px-4 py-1.5 rounded text-sm font-bold flex items-center gap-2 transition-colors",
                      selectedIssueIds.size > 0 
                        ? "bg-green-600 text-white hover:bg-green-500 shadow-sm" 
                        : "bg-slate-700 text-slate-500 cursor-not-allowed"
                    )}
                  >
                     {bulkProcessing ? <Loader2 className="w-3 h-3 animate-spin" /> : <Check className="w-3 h-3" />}
                     Create Selected Issues
                  </button>
               </div>
            )}

            {/* Issues Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {proposedIssues.map((issue) => (
                <div key={issue._id} className={clsx(
                    "border rounded-lg p-5 flex flex-col transition-all relative group shadow-sm",
                    selectedIssueIds.has(issue._id) ? "bg-purple-900/10 border-purple-500/50 ring-1 ring-purple-500/20" : "bg-slate-900/50 border-slate-700 hover:border-purple-500/30"
                  )}>
                  <div className="flex justify-between items-start mb-3">
                    <div className="flex items-center gap-2">
                       <input 
                          type="checkbox"
                          checked={selectedIssueIds.has(issue._id)}
                          onChange={() => toggleSelection(selectedIssueIds, setSelectedIssueIds, issue._id)}
                          className="w-5 h-5 rounded border-slate-600 bg-slate-800 text-purple-600 focus:ring-0 cursor-pointer"
                       />
                       <span className={clsx("text-[10px] font-bold px-1.5 py-0.5 rounded uppercase", 
                          issue.priority === 'High' ? "bg-red-500/10 text-red-400 border border-red-500/20" : "bg-blue-500/10 text-blue-400 border border-blue-500/20"
                       )}>{issue.priority}</span>
                       <span className={clsx("text-[10px] font-bold px-1.5 py-0.5 rounded uppercase border", 
                          issue.effort === 'Large' ? "bg-amber-500/10 text-amber-400 border-amber-500/20" : 
                          issue.effort === 'Medium' ? "bg-slate-700 text-slate-300 border-slate-600" :
                          "bg-green-500/10 text-green-400 border-green-500/20"
                       )}>{issue.effort} Effort</span>
                    </div>
                  </div>
                  
                  <h4 className="font-bold text-white mb-2 ml-1 line-clamp-2">{issue.title}</h4>
                  <p className="text-sm text-slate-400 mb-4 flex-1 ml-1">{issue.reason}</p>
                  
                  <div className="flex flex-wrap gap-1 mb-4 ml-1">
                    {issue.labels.map(l => (
                      <span key={l} className="text-[10px] bg-slate-800 px-1.5 py-0.5 rounded text-slate-400 border border-slate-700">{l}</span>
                    ))}
                  </div>

                  <button 
                    onClick={() => executeCreateIssue(issue)}
                    disabled={bulkProcessing}
                    className="mt-auto w-full border border-purple-500/30 text-purple-400 hover:bg-purple-500/10 py-2 rounded flex items-center justify-center gap-2 text-sm font-medium transition-colors"
                  >
                    <Check className="w-4 h-4" /> Approve Single
                  </button>
                </div>
              ))}
              {proposedIssues.length === 0 && architectStatus === AnalysisStatus.COMPLETE && (
                <div className="col-span-full py-12 text-center text-slate-500 bg-slate-900/30 rounded-lg border border-dashed border-slate-700">
                  <Bot className="w-10 h-10 mx-auto mb-3 opacity-20" />
                  <p>No suggestions found.</p>
                  <p className="text-sm">Try changing the discovery mode or adding guidance.</p>
                </div>
              )}
            </div>
          </div>
        </div>
      )}

      {/* --- OVERSEER TAB --- */}
      {activeTab === 'overseer' && (
        <div className="space-y-6">
          <div className="bg-surface border border-slate-700 rounded-xl p-6">
            <div className="flex justify-between items-center mb-6">
               <div>
                 <h3 className="text-xl font-bold text-white">PR Prioritization & Triage</h3>
                 <p className="text-sm text-slate-400 mt-1">Identifies stale, duplicate, or high-priority PRs.</p>
              </div>
              <div className="flex gap-3">
                {prActions.length > 0 && (
                   <div className="flex items-center gap-3 mr-4 border-r border-slate-700 pr-4">
                      <div className="flex items-center gap-2">
                        <input 
                           type="checkbox"
                           checked={prActions.length > 0 && selectedActionIds.size === prActions.length}
                           onChange={() => toggleSelectAll(prActions.map(i => i._id), selectedActionIds, setSelectedActionIds)}
                           className="w-4 h-4 rounded border-slate-600 bg-slate-800 text-blue-600 focus:ring-0 cursor-pointer"
                        />
                        <span className="text-sm text-slate-300">Select All</span>
                      </div>
                      <button 
                        onClick={executeBulkActions}
                        disabled={selectedActionIds.size === 0 || bulkProcessing}
                        className={clsx(
                          "px-3 py-1.5 rounded text-sm font-medium flex items-center gap-2 transition-colors",
                          selectedActionIds.size > 0 
                            ? "bg-blue-600 text-white hover:bg-blue-500" 
                            : "bg-slate-700 text-slate-400 cursor-not-allowed"
                        )}
                      >
                         {bulkProcessing ? <Loader2 className="w-3 h-3 animate-spin" /> : <Play className="w-3 h-3 fill-current" />}
                         Execute Selected ({selectedActionIds.size})
                      </button>
                   </div>
                 )}
                <button 
                  onClick={runOverseer}
                  disabled={overseerStatus === AnalysisStatus.LOADING || bulkProcessing}
                  className="bg-slate-800 hover:bg-slate-700 text-white px-4 py-2 rounded-lg font-medium flex items-center gap-2 border border-slate-700"
                >
                  {overseerStatus === AnalysisStatus.LOADING ? <Loader2 className="animate-spin w-4 h-4"/> : <Zap className="w-4 h-4"/>}
                  Audit Active PRs
                </button>
              </div>
            </div>

            <div className="space-y-4">
              {prActions.map((item) => (
                <div key={item._id} className={clsx(
                  "border rounded-lg p-4 flex items-center justify-between gap-4 transition-colors",
                  selectedActionIds.has(item._id) ? "bg-blue-900/10 border-blue-500/50" : "bg-slate-900/50 border-slate-700"
                )}>
                  <div className="flex items-center gap-4 flex-1">
                     <input 
                        type="checkbox"
                        checked={selectedActionIds.has(item._id)}
                        onChange={() => toggleSelection(selectedActionIds, setSelectedActionIds, item._id)}
                        className="w-5 h-5 rounded border-slate-600 bg-slate-800 text-blue-600 focus:ring-0 cursor-pointer shrink-0"
                     />
                     <div className="flex-1">
                        <div className="flex items-center gap-3 mb-1">
                          <span className="font-mono text-slate-500 text-sm">#{item.prNumber}</span>
                          <span className={clsx("text-xs font-bold px-2 py-0.5 rounded uppercase", 
                            item.action === 'close' ? "bg-red-500/20 text-red-400" : 
                            item.action === 'prioritize' ? "bg-green-500/20 text-green-400" : "bg-blue-500/20 text-blue-400"
                          )}>{item.action}</span>
                        </div>
                        <p className="text-slate-300 text-sm">{item.reason}</p>
                        {item.suggestedComment && (
                           <p className="text-xs text-slate-500 mt-2 italic border-l-2 border-slate-700 pl-2">"{item.suggestedComment}"</p>
                        )}
                      </div>
                  </div>
                  <button 
                    onClick={() => executePrAction(item)}
                    disabled={bulkProcessing}
                    className={clsx(
                      "px-4 py-2 rounded font-medium text-sm flex items-center gap-2 shrink-0",
                      item.action === 'close' ? "bg-red-900/20 text-red-400 hover:bg-red-900/40" : "bg-slate-700 text-white hover:bg-slate-600"
                    )}
                  >
                    <Play className="w-3 h-3 fill-current" /> Execute
                  </button>
                </div>
              ))}
               {prActions.length === 0 && overseerStatus === AnalysisStatus.COMPLETE && (
                <p className="text-slate-500 text-center py-8">No actions recommended for current PRs.</p>
              )}
            </div>
          </div>
        </div>
      )}

       {/* --- JANITOR TAB --- */}
       {activeTab === 'janitor' && (
        <div className="space-y-6">
          <div className="bg-surface border border-slate-700 rounded-xl p-6">
            <div className="flex justify-between items-center mb-6">
               <div>
                 <h3 className="text-xl font-bold text-white">Smart Linking & Cleanup</h3>
                 <p className="text-sm text-slate-400 mt-1">Detects PRs that solve existing issues but aren't linked.</p>
              </div>
              <div className="flex gap-3">
                 {links.length > 0 && (
                   <div className="flex items-center gap-3 mr-4 border-r border-slate-700 pr-4">
                      <div className="flex items-center gap-2">
                        <input 
                           type="checkbox"
                           checked={links.length > 0 && selectedLinkIds.size === links.length}
                           onChange={() => toggleSelectAll(links.map(i => i._id), selectedLinkIds, setSelectedLinkIds)}
                           className="w-4 h-4 rounded border-slate-600 bg-slate-800 text-green-600 focus:ring-0 cursor-pointer"
                        />
                        <span className="text-sm text-slate-300">Select All</span>
                      </div>
                      <button 
                        onClick={executeBulkLinks}
                        disabled={selectedLinkIds.size === 0 || bulkProcessing}
                        className={clsx(
                          "px-3 py-1.5 rounded text-sm font-medium flex items-center gap-2 transition-colors",
                          selectedLinkIds.size > 0 
                            ? "bg-green-600 text-white hover:bg-green-500" 
                            : "bg-slate-700 text-slate-400 cursor-not-allowed"
                        )}
                      >
                         {bulkProcessing ? <Loader2 className="w-3 h-3 animate-spin" /> : <LinkIcon className="w-3 h-3" />}
                         Link Selected ({selectedLinkIds.size})
                      </button>
                   </div>
                 )}
                <button 
                  onClick={runJanitor}
                  disabled={janitorStatus === AnalysisStatus.LOADING || bulkProcessing}
                  className="bg-slate-800 hover:bg-slate-700 text-white px-4 py-2 rounded-lg font-medium flex items-center gap-2 border border-slate-700"
                >
                  {janitorStatus === AnalysisStatus.LOADING ? <Loader2 className="animate-spin w-4 h-4"/> : <LinkIcon className="w-4 h-4"/>}
                  Find Broken Links
                </button>
              </div>
            </div>

            <div className="space-y-3">
              {links.map((link) => (
                <div key={link._id} className={clsx(
                  "border rounded-lg p-4 flex items-center gap-4 transition-colors",
                  selectedLinkIds.has(link._id) ? "bg-green-900/10 border-green-500/50" : "bg-slate-900/50 border-slate-700"
                )}>
                  <div className="flex items-center gap-4 flex-1">
                     <input 
                        type="checkbox"
                        checked={selectedLinkIds.has(link._id)}
                        onChange={() => toggleSelection(selectedLinkIds, setSelectedLinkIds, link._id)}
                        className="w-5 h-5 rounded border-slate-600 bg-slate-800 text-green-600 focus:ring-0 cursor-pointer shrink-0"
                     />
                     <div className="flex-1 flex items-center gap-4">
                        <div className="flex items-center gap-3 text-slate-400 shrink-0">
                          <span className="bg-blue-900/30 px-2 py-1 rounded text-blue-300 font-mono text-sm">PR #{link.prNumber}</span>
                          <ArrowRight className="w-4 h-4" />
                          <span className="bg-rose-900/30 px-2 py-1 rounded text-rose-300 font-mono text-sm">Issue #{link.issueNumber}</span>
                        </div>
                        <div className="flex-1 border-l border-slate-700 pl-4">
                          <p className="text-sm text-slate-300">{link.reason}</p>
                          <span className="text-xs text-green-500 font-medium">Confidence: {link.confidence}</span>
                        </div>
                     </div>
                  </div>
                  <button 
                     onClick={() => executeLink(link)}
                     disabled={bulkProcessing}
                     className="bg-slate-800 hover:bg-slate-700 text-white px-3 py-2 rounded text-sm flex items-center gap-2 shrink-0"
                  >
                    <LinkIcon className="w-3 h-3" /> Link Now
                  </button>
                </div>
              ))}
               {links.length === 0 && janitorStatus === AnalysisStatus.COMPLETE && (
                <p className="text-slate-500 text-center py-8">No unlinked issues found.</p>
              )}
            </div>
          </div>
        </div>
      )}

    </div>
  );
};

export default Agent;
