
import React, { useState } from 'react';
import { Bot, Sparkles, Trash2, Link as LinkIcon, AlertTriangle, ArrowRight, Check, Play, Zap, Target, Wrench, Search, Code2, FileSearch, Box, TerminalSquare, MessageSquare, Send } from 'lucide-react';
import clsx from 'clsx';
import { fetchIssues, fetchPullRequests, createIssue, updateIssue, addComment, fetchEnrichedPullRequests } from '../services/githubService';
import { suggestStrategicIssues, auditPullRequests, findIssuePrLinks, analyzeJulesSessions } from '../services/geminiService';
import { listSessions, deleteSession, sendMessage } from '../services/julesService';
import { ProposedIssue, PrActionRecommendation, LinkSuggestion, JulesAgentAction } from '../types';
import { useGeminiAnalysis } from '../hooks/useGeminiAnalysis';
import Button from '../components/ui/Button';
import Badge from '../components/ui/Badge';

interface AgentProps {
  repoName: string;
  token: string;
  julesApiKey?: string;
}

type ProposedIssueWithId = ProposedIssue & { _id: string };
type PrActionWithId = PrActionRecommendation & { _id: string };
type LinkSuggestionWithId = LinkSuggestion & { _id: string };
type OperatorActionWithId = JulesAgentAction & { _id: string };

const generateId = () => Math.random().toString(36).substr(2, 9);

const Agent: React.FC<AgentProps> = ({ repoName, token, julesApiKey }) => {
  const [activeTab, setActiveTab] = useState<'architect' | 'overseer' | 'janitor' | 'operator'>('architect');
  const [bulkProcessing, setBulkProcessing] = useState(false);
  
  // Architect State
  const [proposedIssues, setProposedIssues] = useState<ProposedIssueWithId[]>([]);
  const [selectedIssueIds, setSelectedIssueIds] = useState<Set<string>>(new Set());
  const [discoveryMode, setDiscoveryMode] = useState<string>('strategic');
  const [userGuidance, setUserGuidance] = useState('');
  
  // Overseer State
  const [prActions, setPrActions] = useState<PrActionWithId[]>([]);
  const [selectedActionIds, setSelectedActionIds] = useState<Set<string>>(new Set());

  // Janitor State
  const [links, setLinks] = useState<LinkSuggestionWithId[]>([]);
  const [selectedLinkIds, setSelectedLinkIds] = useState<Set<string>>(new Set());

  // Operator State
  const [operatorActions, setOperatorActions] = useState<OperatorActionWithId[]>([]);
  const [selectedOperatorIds, setSelectedOperatorIds] = useState<Set<string>>(new Set());

  // Use custom analysis hooks
  const architectAnalysis = useGeminiAnalysis(async () => {
     const [issues, prs] = await Promise.all([fetchIssues(repoName, token, 'open'), fetchPullRequests(repoName, token, 'open')]);
     const suggestions = await suggestStrategicIssues(issues, prs, discoveryMode, userGuidance);
     const withIds = suggestions.map(s => ({ ...s, _id: generateId() }));
     setProposedIssues(withIds);
     setSelectedIssueIds(new Set());
     return withIds;
  });

  const overseerAnalysis = useGeminiAnalysis(async () => {
     const prs = await fetchPullRequests(repoName, token, 'open');
     const actions = await auditPullRequests(prs);
     const withIds = actions.map(a => ({ ...a, _id: generateId() }));
     setPrActions(withIds);
     setSelectedActionIds(new Set());
     return withIds;
  });

  const janitorAnalysis = useGeminiAnalysis(async () => {
     const [issues, prs] = await Promise.all([fetchIssues(repoName, token, 'open'), fetchPullRequests(repoName, token, 'open')]);
     const matches = await findIssuePrLinks(issues, prs);
     const withIds = matches.map(m => ({ ...m, _id: generateId() }));
     setLinks(withIds);
     setSelectedLinkIds(new Set());
     return withIds;
  });

  const operatorAnalysis = useGeminiAnalysis(async () => {
    if (!julesApiKey) throw new Error("Jules API Key required");
    const [sessions, prs] = await Promise.all([
      listSessions(julesApiKey),
      fetchEnrichedPullRequests(repoName, token) // Fetch enriched PRs to check for conflicts
    ]);
    const actions = await analyzeJulesSessions(sessions, prs);
    const withIds = actions.map(a => ({ ...a, _id: generateId() }));
    setOperatorActions(withIds);
    setSelectedOperatorIds(new Set());
    return withIds;
  });

  // --- Actions ---

  const executeBulkIssues = async () => {
    if (!token) return alert('Token required');
    setBulkProcessing(true);
    const selected = proposedIssues.filter(i => selectedIssueIds.has(i._id));
    const successIds: string[] = [];
    
    for (const issue of selected) {
      try {
        const finalLabels = [...issue.labels, `effort:${issue.effort.toLowerCase()}`];
        await createIssue(repoName, token, {
          title: issue.title,
          body: issue.body + `\n\n*Generated by RepoAuditor Agent (${discoveryMode})*`,
          labels: finalLabels
        });
        successIds.push(issue._id);
      } catch (e) { console.error(e); }
    }
    setProposedIssues(prev => prev.filter(i => !successIds.includes(i._id)));
    setSelectedIssueIds(prev => { const next = new Set(prev); successIds.forEach(id => next.delete(id)); return next; });
    setBulkProcessing(false);
  };

  const executeBulkActions = async () => {
    if (!token) return alert('Token required');
    setBulkProcessing(true);
    const selected = prActions.filter(i => selectedActionIds.has(i._id));
    const successIds: string[] = [];

    for (const item of selected) {
      try {
         if (item.action === 'close') {
            await updateIssue(repoName, token, item.prNumber, { state: 'closed' });
            if (item.suggestedComment) await addComment(repoName, token, item.prNumber, item.suggestedComment);
         } else if (item.action === 'comment' && item.suggestedComment) {
            await addComment(repoName, token, item.prNumber, item.suggestedComment);
         }
         successIds.push(item._id);
      } catch (e) { console.error(e); }
    }
    setPrActions(prev => prev.filter(i => !successIds.includes(i._id)));
    setSelectedActionIds(prev => { const next = new Set(prev); successIds.forEach(id => next.delete(id)); return next; });
    setBulkProcessing(false);
  };

  const executeBulkLinks = async () => {
    if (!token) return alert('Token required');
    setBulkProcessing(true);
    const selected = links.filter(i => selectedLinkIds.has(i._id));
    const successIds: string[] = [];
    for (const link of selected) {
      try {
        const comment = `Closes #${link.issueNumber}\n\n*Linked by RepoAuditor Agent*`;
        await addComment(repoName, token, link.prNumber, comment);
        successIds.push(link._id);
      } catch (e) { console.error(e); }
    }
    setLinks(prev => prev.filter(i => !successIds.includes(i._id)));
    setSelectedLinkIds(prev => { const next = new Set(prev); successIds.forEach(id => next.delete(id)); return next; });
    setBulkProcessing(false);
  };

  const executeBulkOperator = async () => {
    if (!julesApiKey) return alert("Jules API Key required");
    setBulkProcessing(true);
    const selected = operatorActions.filter(i => selectedOperatorIds.has(i._id));
    const successIds: string[] = [];

    for (const item of selected) {
      try {
        const shortName = item.sessionName.split('/').pop() || item.sessionName;
        if (item.action === 'delete') {
           await deleteSession(julesApiKey, shortName);
        } else if (item.action === 'message' || item.action === 'recover') {
           const msg = item.suggestedCommand || "Please check status.";
           await sendMessage(julesApiKey, shortName, msg);
        } else if (item.action === 'publish') {
           await sendMessage(julesApiKey, shortName, "Please publish the pull request now.");
        }
        successIds.push(item._id);
      } catch (e) { console.error(e); }
    }
    setOperatorActions(prev => prev.filter(i => !successIds.includes(i._id)));
    setSelectedOperatorIds(prev => { const next = new Set(prev); successIds.forEach(id => next.delete(id)); return next; });
    setBulkProcessing(false);
  };

  // Helper
  const toggleSet = (setIds: Set<string>, setFunction: (s: Set<string>) => void, id: string) => {
    const next = new Set(setIds);
    if (next.has(id)) next.delete(id); else next.add(id);
    setFunction(next);
  };

  const toggleAll = (ids: string[], currentSet: Set<string>, setFunction: (s: Set<string>) => void) => {
    setFunction(currentSet.size === ids.length ? new Set() : new Set(ids));
  };

  const discoveryOptions = [
    { value: 'strategic', label: 'Strategic Gaps', icon: Target },
    { value: 'tech_debt', label: 'Tech Debt (General)', icon: Wrench },
    { value: 'quick_win', label: 'Quick Wins', icon: Zap },
    { value: 'code_reuse', label: 'Code Reuse & Utilities', icon: Code2 },
    { value: 'dead_code', label: 'Dead Code / Deprecation', icon: Trash2 },
    { value: 'readability', label: 'Naming & Readability', icon: FileSearch },
    { value: 'maintainability', label: 'Maintenance & Updates', icon: Box },
  ];

  return (
    <div className="max-w-6xl mx-auto pb-20">
      <div className="flex items-center gap-3 mb-8">
        <div className="bg-purple-500/20 p-3 rounded-lg text-purple-400"><Bot className="w-8 h-8" /></div>
        <div><h2 className="text-2xl font-bold text-white">Repo Agent</h2><p className="text-slate-400">Autonomous assistant to suggest work, triage PRs, and clean up the repo.</p></div>
      </div>

      {/* Tabs */}
      <div className="flex border-b border-slate-700 mb-8 overflow-x-auto">
        {[
          { id: 'architect', label: 'Architect (Discovery)', icon: Sparkles },
          { id: 'overseer', label: 'Overseer (PR Triage)', icon: AlertTriangle },
          { id: 'janitor', label: 'Janitor (Cleanup)', icon: Trash2 },
          { id: 'operator', label: 'Operator (Session Ops)', icon: TerminalSquare },
        ].map((tab) => (
          <button key={tab.id} onClick={() => setActiveTab(tab.id as any)} className={clsx("flex items-center gap-2 px-6 py-4 font-medium transition-colors border-b-2 whitespace-nowrap", activeTab === tab.id ? "border-primary text-primary" : "border-transparent text-slate-400 hover:text-white")}>
            <tab.icon className="w-4 h-4" />{tab.label}
          </button>
        ))}
      </div>

      {/* --- ARCHITECT TAB --- */}
      {activeTab === 'architect' && (
        <div className="space-y-6">
          <div className="bg-surface border border-slate-700 rounded-xl p-6">
            {/* Control Panel */}
            <div className="bg-slate-900/50 p-5 rounded-lg border border-slate-700 mb-6 grid grid-cols-1 lg:grid-cols-12 gap-4 items-end">
               <div className="lg:col-span-3">
                 <label className="block text-xs font-bold text-slate-500 uppercase mb-2">Discovery Mode</label>
                 <div className="relative">
                   <select value={discoveryMode} onChange={(e) => setDiscoveryMode(e.target.value)} className="w-full bg-slate-800 border border-slate-600 text-white text-sm rounded-lg p-2.5 appearance-none focus:ring-1 focus:ring-primary">
                     {discoveryOptions.map(opt => <option key={opt.value} value={opt.value}>{opt.label}</option>)}
                   </select>
                   <div className="absolute inset-y-0 right-0 flex items-center pr-3 pointer-events-none text-slate-400"><Search className="w-4 h-4" /></div>
                 </div>
               </div>
               <div className="lg:col-span-7">
                  <label className="block text-xs font-bold text-slate-500 uppercase mb-2">User Guidance (Optional)</label>
                  <input type="text" value={userGuidance} onChange={(e) => setUserGuidance(e.target.value)} placeholder="E.g. Focus on authentication..." className="w-full bg-slate-800 border border-slate-600 text-white text-sm rounded-lg p-2.5 focus:ring-1 focus:ring-primary" />
               </div>
               <div className="lg:col-span-2">
                 <Button variant="primary" className="w-full" onClick={() => architectAnalysis.run()} isLoading={architectAnalysis.status === 'LOADING' || bulkProcessing} icon={Sparkles}>Generate</Button>
               </div>
            </div>

            {/* Actions Bar */}
            {proposedIssues.length > 0 && (
               <div className="flex items-center justify-between mb-4 bg-slate-800/30 p-3 rounded-lg border border-slate-700/50">
                  <div className="flex items-center gap-3">
                     <div className="flex items-center gap-2">
                       <input type="checkbox" checked={proposedIssues.length > 0 && selectedIssueIds.size === proposedIssues.length} onChange={() => toggleAll(proposedIssues.map(i => i._id), selectedIssueIds, setSelectedIssueIds)} className="w-4 h-4 rounded border-slate-600 bg-slate-800 text-purple-600 cursor-pointer" />
                       <span className="text-sm text-slate-300">Select All</span>
                     </div>
                     <span className="text-sm text-slate-400">Found {proposedIssues.length} suggestions</span>
                  </div>
                  <Button variant="success" size="sm" onClick={executeBulkIssues} disabled={selectedIssueIds.size === 0 || bulkProcessing} isLoading={bulkProcessing} icon={Check}>Create Selected</Button>
               </div>
            )}

            {/* Issues Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {proposedIssues.map((issue) => (
                <div key={issue._id} className={clsx("border rounded-lg p-5 flex flex-col transition-all relative group shadow-sm", selectedIssueIds.has(issue._id) ? "bg-purple-900/10 border-purple-500/50 ring-1 ring-purple-500/20" : "bg-slate-900/50 border-slate-700 hover:border-purple-500/30")}>
                  <div className="flex justify-between items-start mb-3">
                    <div className="flex items-center gap-2">
                       <input type="checkbox" checked={selectedIssueIds.has(issue._id)} onChange={() => toggleSet(selectedIssueIds, setSelectedIssueIds, issue._id)} className="w-5 h-5 rounded border-slate-600 bg-slate-800 text-purple-600 cursor-pointer" />
                       <Badge variant={issue.priority === 'High' ? 'red' : 'blue'}>{issue.priority}</Badge>
                       <Badge variant="green">{issue.effort}</Badge>
                    </div>
                  </div>
                  <h4 className="font-bold text-white mb-2 ml-1 line-clamp-2">{issue.title}</h4>
                  <p className="text-sm text-slate-400 mb-4 flex-1 ml-1">{issue.reason}</p>
                  <div className="flex flex-wrap gap-1 mb-4 ml-1">{issue.labels.map(l => <span key={l} className="text-[10px] bg-slate-800 px-1.5 py-0.5 rounded text-slate-400 border border-slate-700">{l}</span>)}</div>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* --- OVERSEER TAB --- */}
      {activeTab === 'overseer' && (
        <div className="space-y-6">
          <div className="bg-surface border border-slate-700 rounded-xl p-6">
            <div className="flex justify-between items-center mb-6">
               <h3 className="text-xl font-bold text-white">PR Prioritization & Triage</h3>
               <div className="flex gap-3">
                <Button variant="secondary" onClick={() => overseerAnalysis.run()} isLoading={overseerAnalysis.status === 'LOADING' || bulkProcessing} icon={Zap}>Audit PRs</Button>
               </div>
            </div>

             {/* Actions Bar */}
             {prActions.length > 0 && (
               <div className="flex items-center justify-between mb-4 bg-slate-800/30 p-3 rounded-lg border border-slate-700/50">
                  <div className="flex items-center gap-3">
                     <div className="flex items-center gap-2">
                       <input type="checkbox" checked={prActions.length > 0 && selectedActionIds.size === prActions.length} onChange={() => toggleAll(prActions.map(i => i._id), selectedActionIds, setSelectedActionIds)} className="w-4 h-4 rounded border-slate-600 bg-slate-800 text-blue-600 cursor-pointer" />
                       <span className="text-sm text-slate-300">Select All</span>
                     </div>
                     <span className="text-sm text-slate-400">Found {prActions.length} recommendations</span>
                  </div>
                  <Button variant="primary" size="sm" onClick={executeBulkActions} disabled={selectedActionIds.size === 0 || bulkProcessing} isLoading={bulkProcessing} icon={Play}>Execute Selected</Button>
               </div>
            )}

            <div className="space-y-4">
              {prActions.map((item) => (
                <div key={item._id} className={clsx("border rounded-lg p-4 flex items-center justify-between gap-4", selectedActionIds.has(item._id) ? "bg-blue-900/10 border-blue-500/50" : "bg-slate-900/50 border-slate-700")}>
                  <div className="flex items-center gap-4 flex-1">
                     <input type="checkbox" checked={selectedActionIds.has(item._id)} onChange={() => toggleSet(selectedActionIds, setSelectedActionIds, item._id)} className="w-5 h-5 rounded border-slate-600 bg-slate-800 text-blue-600 cursor-pointer shrink-0" />
                     <div className="flex-1">
                        <div className="flex items-center gap-3 mb-1">
                          <span className="font-mono text-slate-500 text-sm">#{item.prNumber}</span>
                          <Badge variant={item.action === 'close' ? 'red' : item.action === 'prioritize' ? 'green' : 'blue'}>{item.action}</Badge>
                        </div>
                        <p className="text-slate-300 text-sm">{item.reason}</p>
                        {item.suggestedComment && <p className="text-xs text-slate-500 mt-2 italic border-l-2 border-slate-700 pl-2">"{item.suggestedComment}"</p>}
                      </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

       {/* --- JANITOR TAB --- */}
       {activeTab === 'janitor' && (
        <div className="space-y-6">
          <div className="bg-surface border border-slate-700 rounded-xl p-6">
            <div className="flex justify-between items-center mb-6">
               <h3 className="text-xl font-bold text-white">Smart Linking & Cleanup</h3>
               <div className="flex gap-3">
                 <Button variant="secondary" onClick={() => janitorAnalysis.run()} isLoading={janitorAnalysis.status === 'LOADING' || bulkProcessing} icon={LinkIcon}>Find Broken Links</Button>
               </div>
            </div>

            {/* Actions Bar */}
            {links.length > 0 && (
               <div className="flex items-center justify-between mb-4 bg-slate-800/30 p-3 rounded-lg border border-slate-700/50">
                  <div className="flex items-center gap-3">
                     <div className="flex items-center gap-2">
                       <input type="checkbox" checked={links.length > 0 && selectedLinkIds.size === links.length} onChange={() => toggleAll(links.map(i => i._id), selectedLinkIds, setSelectedLinkIds)} className="w-4 h-4 rounded border-slate-600 bg-slate-800 text-green-600 cursor-pointer" />
                       <span className="text-sm text-slate-300">Select All</span>
                     </div>
                     <span className="text-sm text-slate-400">Found {links.length} suggestions</span>
                  </div>
                  <Button variant="success" size="sm" onClick={executeBulkLinks} disabled={selectedLinkIds.size === 0 || bulkProcessing} isLoading={bulkProcessing} icon={LinkIcon}>Link Selected</Button>
               </div>
            )}

            <div className="space-y-3">
              {links.map((link) => (
                <div key={link._id} className={clsx("border rounded-lg p-4 flex items-center gap-4", selectedLinkIds.has(link._id) ? "bg-green-900/10 border-green-500/50" : "bg-slate-900/50 border-slate-700")}>
                  <input type="checkbox" checked={selectedLinkIds.has(link._id)} onChange={() => toggleSet(selectedLinkIds, setSelectedLinkIds, link._id)} className="w-5 h-5 rounded border-slate-600 bg-slate-800 text-green-600 cursor-pointer shrink-0" />
                  <div className="flex-1 flex items-center gap-4">
                     <div className="flex items-center gap-3 text-slate-400 shrink-0">
                       <Badge variant="blue">PR #{link.prNumber}</Badge>
                       <ArrowRight className="w-4 h-4" />
                       <Badge variant="red">Issue #{link.issueNumber}</Badge>
                     </div>
                     <div className="flex-1 border-l border-slate-700 pl-4">
                       <p className="text-sm text-slate-300">{link.reason}</p>
                       <span className="text-xs text-green-500 font-medium">Confidence: {link.confidence}</span>
                     </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* --- OPERATOR TAB --- */}
      {activeTab === 'operator' && (
        <div className="space-y-6">
          <div className="bg-surface border border-slate-700 rounded-xl p-6">
            <div className="flex justify-between items-center mb-6">
               <h3 className="text-xl font-bold text-white">Session Analysis & Ops</h3>
               <div className="flex gap-3">
                 <Button variant="secondary" onClick={() => operatorAnalysis.run()} isLoading={operatorAnalysis.status === 'LOADING' || bulkProcessing} icon={TerminalSquare}>Analyze Sessions</Button>
               </div>
            </div>

            {/* Actions Bar */}
            {operatorActions.length > 0 && (
               <div className="flex items-center justify-between mb-4 bg-slate-800/30 p-3 rounded-lg border border-slate-700/50">
                  <div className="flex items-center gap-3">
                     <div className="flex items-center gap-2">
                       <input type="checkbox" checked={operatorActions.length > 0 && selectedOperatorIds.size === operatorActions.length} onChange={() => toggleAll(operatorActions.map(i => i._id), selectedOperatorIds, setSelectedOperatorIds)} className="w-4 h-4 rounded border-slate-600 bg-slate-800 text-purple-600 cursor-pointer" />
                       <span className="text-sm text-slate-300">Select All</span>
                     </div>
                     <span className="text-sm text-slate-400">Found {operatorActions.length} recommendations</span>
                  </div>
                  <Button variant="success" size="sm" onClick={executeBulkOperator} disabled={selectedOperatorIds.size === 0 || bulkProcessing} isLoading={bulkProcessing} icon={Play}>Run Recommended Actions</Button>
               </div>
            )}

            <div className="space-y-3">
              {operatorActions.map((item) => (
                <div key={item._id} className={clsx("border rounded-lg p-4 flex gap-4", selectedOperatorIds.has(item._id) ? "bg-purple-900/10 border-purple-500/50" : "bg-slate-900/50 border-slate-700")}>
                  <div className="pt-1">
                    <input type="checkbox" checked={selectedOperatorIds.has(item._id)} onChange={() => toggleSet(selectedOperatorIds, setSelectedOperatorIds, item._id)} className="w-5 h-5 rounded border-slate-600 bg-slate-800 text-purple-600 cursor-pointer shrink-0" />
                  </div>
                  <div className="flex-1">
                    <div className="flex items-center justify-between mb-2">
                       <div className="flex items-center gap-3">
                         <span className="font-mono text-xs text-slate-500">{item.sessionName.split('/').pop()}</span>
                         <Badge variant={item.action === 'delete' ? 'red' : item.action === 'publish' ? 'green' : 'blue'}>{item.action}</Badge>
                       </div>
                    </div>
                    <p className="text-slate-300 text-sm mb-2">{item.reason}</p>
                    {item.suggestedCommand && (
                       <div className="bg-black/30 p-2 rounded border border-slate-800 font-mono text-xs text-green-400 flex items-start gap-2">
                          <TerminalSquare className="w-3 h-3 mt-0.5 shrink-0" />
                          <span className="break-all">{item.suggestedCommand}</span>
                       </div>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default Agent;
